### PR TITLE
Fix not to indent when the content is not JSON object

### LINKED ISSUE #36: dogma returns error invalid json when called dogma cat --jsonpath
These steps below I copied from [tutorial](https://line.github.io/centraldogma/client-cli.html).

## Reproduce steps:

start centraldogma with docker command:

```
$ docker run -p 36462:36462 --name dogma --rm line/centraldogma
```

Then running with following steps:

```
$ cat test.sh
#!/bin/sh

conn='http://localhost:36462'

./dogma -c $conn new projFoo
./dogma -c $conn new projFoo/repoA
echo '{"a":"b"}' > a.json
./dogma -c $conn put projFoo/repoA/samples/a.json a.json -m 'Add a.json'
./dogma -c $conn ls
./dogma -c $conn cat projFoo/repoA/samples/a.json
./dogma -c $conn cat --jsonpath '$.a' projFoo/repoA/samples/a.json
```

## Expected result: 

The `./dogma -c http://localhost:36462 cat --jsonpath '$.a'` in the last step should returns `"b"` as mentioned in tutorial website.

## Actual Result

```
invalid character 'b' looking for beginning of value
```

## Dogma version:

```
$ ./dogma
Central Dogma version 0.41.1 (241c5a8)
```

And found it in current master branch.

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
Currently, we indent JSON content if the `EntryType` is `JSON`.
However, the content can be just a string when we use JSON path.

Modification:
- Do not indent when the content is not JSON object

Result:
- Fix #36
- You no longer see parsing error when fetching JSON content using JSON path

### CODE REVIEW

File: internal/app/dogma/get_cmd.go [hunk 1]
```diff
@@ -49,11 +49,18 @@ func (gf *getFileCommand) execute(c *cli.Context) error {
 	defer fd.Close()
 
 	if entry.Type == centraldogma.JSON {
-		b, err := marshalIndent(entry.Content)
-		if err != nil {
+		var b []byte
+		if isJSON(entry.Content) {
+			b, err = marshalIndent(entry.Content)
```
Comment (ikhoon) [inline internal/app/dogma/get_cmd.go]: I think this workaround is good but it has a lot of duplicated code.
How about moving the logic into [`marshalIndent()`](https://github.com/ikhoon/centraldogma-go/blob/52ed8f59381263a82adcde3fa11b7cbadfa097e0/internal/app/dogma/util.go#L280) method?
```go
func marshalIndent(src []byte) ([]byte, error) {
	if isJSON(src) { ... }
	dst := new(bytes.Buffer)
	err := json.Indent(dst, src, "", "  ")
	return dst.Bytes(), err
}
```

Comment (minwoox) [reply internal/app/dogma/get_cmd.go]: Yeah, that a good idea. But I have to change the name `marshalIndent` to something else. Any suggestion for that?

Comment (minwoox) [reply internal/app/dogma/get_cmd.go]: Do you mean that `marsharIndent` returns `nil` when the content is a string? so the code should be
```go
b, err = marshalIndent(entry.Content)
if err != nil {
  return err
}
if b == nil {
  b = entry.Content
}
```

Comment (ikhoon) [reply internal/app/dogma/get_cmd.go]: > But I have to change the name marshalIndent to something else. Any suggestion for that?
How about adding `safeMarshalIndent()`? 😀
```go
func safeMarshalIndent(src []byte) ([]byte, error) {
	if isJSON(src) {
		return marshalIndent(src)
	} else {
		return src, nil
	}
}
```

Comment (minwoox) [reply internal/app/dogma/get_cmd.go]: I like it. Thanks!

File: internal/app/dogma/util.go [hunk 2]
```diff
@@ -277,8 +276,16 @@ func marshalIndentObject(data interface{}) ([]byte, error) {
...
+		dst := new(bytes.Buffer)
+		_ = json.Indent(dst, src, "", "  ")
+		return dst.Bytes()
+	}
+	return src
+}
+
+func isJSON(b []byte) bool {
+	var holder map[string]interface{}
+	return json.Unmarshal(b, &holder) == nil
```
Comment (wingyplus) [inline internal/app/dogma/util.go]: I think in this case we can use `json.Valid` to validate `b`. (https://golang.org/pkg/encoding/json/#Valid)

Comment (minwoox) [reply internal/app/dogma/util.go]: Ah let me use that. Thanks!

File: internal/app/dogma/watch_cmd.go [hunk 3]
```diff
@@ -88,7 +83,10 @@ func (wc *watchCommand) execute(c *cli.Context) error {
 	}
 
 	// start watching
-	fw.Watch(listener)
+	err = fw.Watch(listener)
+	if err != nil {
```
Comment (wingyplus) [inline internal/app/dogma/watch_cmd.go]: I think it's better to move error into if scope: 

```
if err := fw.Watch(listener); err != nil {
  return err
}
```

**Comment by trustin** [comment]
Thanks, reviewers!
